version: '3.9'
services:
  postgres:
    image: postgres:14.5
    networks:
      - db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  postgresadmin:
    image: ghcr.io/jimmylevell/postgres/levell_pgadmin:latest
    ports:
      - "8080:80"
    networks:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@levell.ch
      PGADMIN_DEFAULT_PASSWORD: password

networks:
  db:
